var repsCustom = {
    Aegis: "Aegis",
    Alacrity: "Alacrity",
    Fury: "Fury",
    Might: "Might",
    Protection: "Protection",
    Quickness: "Quickness",
    Regeneration: "Regeneration",
    Resistance: "Resistance",
    Retaliation: "Retaliation",
    Stability: "Stability",
    Swiftness: "Swiftness",
    Vigor: "Vigor",
    ChaosAura: "Chaos Aura",
    DarkAura: "Dark Aura",
    FireAura: "Fire Aura",
    FrostAura: "Frost Aura",
    LightAura: "Light Aura",
    MagneticAura: "Magnetic Aura",
    ShockingAura: "Shocking Aura",
    Bleeding: "Bleeding",
    Blinded: "Blinded",
    Burning: "Burning",
    Chilled: "Chilled",
    Confusion: "Confusion",
    Crippled: "Crippled",
    Fear: "Fear",
    Immobilise: "Immobilise",
    Poison: "Poison",
    Slow: "Slow",
    Taunt: "Taunt",
    Torment: "Torment",
    Vulnerability: "Vulnerability",
    Weakness: "Weakness",
    Superspeed: "Superspeed",
    Barrier: "Barrier",
    Invulnerable: "Invulnerable",
    Stealth: "Stealth",
    Revealed: "Revealed",
    Stunbreak: "Stunbreak",
    Daze: "Daze",
    Float: "Float",
    Knockback: "Knockback",
    Knockdown: "Knockdown",
    Launch: "Launch",
    Sink: "Sink",
    Stun: "Stun",
    Holosmith: "Holosmith",
    Berserker: "Berserker",
    Chronomancer: "Chronomancer",
    Daredevil: "Daredevil",
    Deadeye: "Deadeye",
    Dragonhunter: "Dragonhunter",
    Druid: "Druid",
    Elementalist: "Elementalist",
    Engineer: "Engineer",
    Firebrand: "Firebrand",
    Guardian: "Guardian",
    Herald: "Herald",
    Scrapper: "Scrapper",
    Mesmer: "Mesmer",
    Mirage: "Mirage",
    Necromancer: "Necromancer",
    Ranger: "Ranger",
    Reaper: "Reaper",
    Renegade: "Renegade",
    Revenant: "Revenant",
    Soulbeast: "Soulbeast",
    Spellbreaker: "Spellbreaker",
    Tempest: "Tempest",
    Thief: "Thief",
    Warrior: "Warrior",
    Weaver: "Weaver",
    Scourge: "Scourge"


};